### ISSUE TITLE
Handling tip convolution errors in grain sizing

### ISSUE THREAD

**Issue by bobturneruk** [AFM-SPM/TopoStats#101]
**Is your feature request related to a problem? Please describe.**
We are working with shapes that approximate to the outline of simple geometric objects e.g. the outline of a square. Depending on the size of the AFM tip shapes appear larger or smaller. This can be corrected experimentally, but we'd like to be able to compare data across different tip sizes.

![image](https://user-images.githubusercontent.com/34244196/162195762-84e9be33-5a7b-41da-b50d-6e6aeca27c18.png)

Small tip left, big tip right.

**Describe the solution you'd like**
Fitting the outline of the shape at it's highest point (like a ridge running round the shape) might give us a true object size that's independent of tip size.

![image](https://user-images.githubusercontent.com/34244196/162196710-283ab55a-ce02-44d2-8c00-6aa5004c78d1.png)

**Describe alternatives you've considered**
Another approach would be deconvolution, but this would maybe need the tip size which we don't generally know.

**Comment by bobturneruk** [comment]
This would need someone familiar with topostats code for tracing loops of DNA to develop further.

**Comment by LunchBobs** [comment]
@bobturneruk I've accidentally added a duplicate of this issue, but put a bit more detail in. Is it possible to delete this one?

**Comment by bobturneruk** [comment]
Sure @LunchBobs - I'll just close this and mention #108 so we have a record that they're linked.
