### ISSUE TITLE
Characterising complex box molecules with wiggling arms

### ISSUE THREAD

**Issue by LunchBobs** [AFM-SPM/TopoStats#109]
**Is your feature request related to a problem? Please describe.**
We are imaging some complex molecules that are box shapes with wiggling arms projecting from two opposite corners. The box is mostly square, but the wiggling arms, which can be of differing lengths but are usually at least as long as the box sides flop about taking different conformations. 

![image](https://user-images.githubusercontent.com/99015433/164688226-70a66b06-c5c9-4ab3-bdd1-24db487f9dd6.png)

We'd like to be able to characterise this statistically. Gwyddion has a function to calculate the aspect ratio of the grains (molecules) and this provides some useful data, on rough conformation. It does this by calculating the min and max bounding size of the molecules and dividing the former by the latter.

![image](https://user-images.githubusercontent.com/99015433/164688532-0116cde4-11d8-4282-b4c3-0b9cff529beb.png)

**Describe the solution you'd like**

It would be ideal if we could get information about two things; the box (green) and the arms (red).

![image](https://user-images.githubusercontent.com/99015433/164689008-ce8bde65-c762-456b-bb86-db91143592c3.png)

If we could determine to box area, and maybe even the degree of skew that would be great.

If we could determine the contour length of the arms, maybe even measuring the curviness of them would be amazing.

**Describe alternatives you've considered**

Another simpler solution would just to measure the whole length of the molecule and that would give us some more useful information

![image](https://user-images.githubusercontent.com/99015433/164693401-ceb2d138-3246-42a0-b9fc-ed5ce0a79b5e.png)

**Comment by MaxGamill-Sheffield** [comment]
Seems to be included with the additions to the `disorderedTrace` module which provides measurements (i.e. length, connected components, no. endpoints / junctions) on individual branches of a skeletonised molecule
