### ISSUE TITLE
dev-remove-gwyddion: Remove large objects

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#117]
**Is your feature request related to a problem? Please describe.**
Overly large objects are currently captured by this branch of TopoStats.

**Describe the solution you'd like**
Similar to the suggested solution to #114, we can make a variable 'max_deviation' and use this along with the median grain areas (after removing grains < minsize) to filter out grains that are > max_deviation * median grain area. Just like the current TopoStats.

**Comment by ns-rse** [comment]
Closing as large objects are removed via upper thresholds.
