### ISSUE TITLE
Unit tests and refactoring of grainstats.py

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#122]
@SylviaWhittle has re-written the code that calculates grain statistics (see branch/file [`dev-remove-gwyddion/topostats/grainstats.py`](https://github.com/AFM-SPM/TopoStats/blob/dev-remove-gwyddion/topostats/grainstats.py)).

We need unit-tests in place and there may be a little refactoring that can be done at the same time.

Once complete it can be merged along with #103 and #118 into `dev` to form a basis for a working version in Python 3 that doesn't rely on Gwyddion.

**Comment by SylviaWhittle** [comment]
The legitimacy of the calculations is not confirmed just yet. There have been some conflicts between the values that are computed in grainstats.py and Gwyddion, so there will probably be small changes to the calculations, though nothing major I think. @MaxGamill-Sheffield and I are looking into this. 

Should the unit tests and refactoring be done and then we add hotfixes for the calculation methods in the interests of progress and efficiency @ns-rse ?

**Comment by ns-rse** [comment]
I'll write unit-tests with what is in place now, if the underlying calculations then change these target values we can modify the targets of the test to reflect that once the methods to be used are decided upon.
