### ISSUE TITLE
Variable "minarea" representing a length rather than an area

### ISSUE THREAD

**Issue by Jean-Du** [AFM-SPM/TopoStats#135]
**Describe the bug**
The variable "minarea" used in the config file is supposed to be "the minimum size for grain determination", but it is in fact a length in metres. To determine the minimum size, the "minarea" is divded by the length of a pixel, and the resultant number of pixels is used as the selection criteria for masking--grains with fewer pixels than that number are not masked.

**To Reproduce**
Inapplicable

**Expected behavior**

The default values of minarea need to be changed to represent actual areas, and they need to be divided by the area of a pixel rather than its length in line 235 of pygwytracing.py. 

**Output**
Inapplicable

**(Not required if using Docker) Your computer configuration (please complete the following information):**
Inapplicable

**Additional context**

**Comment by ns-rse** [comment]
Closing as agreed we have dealt with this already.
