### ISSUE TITLE
Parity between gwyddion TopoStats grain statistics and `dev`

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#145]
**Is your feature request related to a problem? Please describe.**
`dev` does not produce grain statistics that are in parity with the old gwyddion TopoStats grain statistics. 

**Describe the solution you'd like**
Parity needs to be made between them before continuing with development

A summary of the statistic discrepancies:
![image](https://user-images.githubusercontent.com/86117496/168825413-55d276e7-432f-4e5d-90d4-510feebddced.png)

**Comment by bobturneruk** [comment]
@ns-rse can you look at this one, please? Hopefully with a shorter development cycle and smaller PRs in future user / acceptance testing can take place against `dev` and avoid this kind of thing. Kind of to be expected at this stage, though. Good spot @SylviaWhittle!

**Comment by SylviaWhittle** [comment]
@bobturneruk I've made the necessary changes, just adding the issue for documentation purposes. Making a PR now.

**Comment by bobturneruk** [comment]
Splendid! Looking forward to it.

**Comment by SylviaWhittle** [comment]
Completed as of #147
