### ISSUE TITLE
Topostats 2.0 : More intelligent size thresholding

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#152]
**Is your feature request related to a problem? Please describe.**
After discussions with the team, it was decided that a more intelligent size thresholding method should be implemented.

**Describe the solution you'd like**
Size thresholding should be done by first removing tiny grains. The threshold for this should be set by the user using the configuration yaml file. After this, a typical standard deviation based upper and lower thresholding method should be used to remove anomalies. 

**Describe alternatives you've considered**
N/A

**Comment by ns-rse** [comment]
Closing we now undertake two rounds of thresholding the first removes "noise" from very small particles before then applying the users-specified (or default) chosen threshold method.
