### ISSUE TITLE
Align output from new topotracing.py with dnatracing.py

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#156]
With the removal of depending on Gwydion we are now at the next step of ensuring the output produced through processing with scikit-image is suitable to be passed on to next step in analysis which is conducted with `tracing/dnatracing.py`.

The `dnaTrace` class takes the following arguments...

* `full_image_data` 
* `gwyddion_grains`
* `afm_image_name`
* `pixel_size`
* `number_of_columns`
* `number_of_rows`

...and so we need to provide those from the output of `topotracing.py`.

To achieve this I will run the old `pygwytracing.py` based code and determine what each of these are and how to extract them from scikit-image pipeline.

**Comment by bobturneruk** [comment]
Good work and good plan.
