### ISSUE TITLE
Dev: "01-raw_heightmap.png" plots processed data instead of raw height data

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#159]
**Describe the bug**
The output plot produced to show the raw heightmap (01-raw_heightmap.png) shows data that looks like it has undergone some processing already and thus is not the raw height data from the SPM file.

**To Reproduce**

- Command used to run topostats e.g. `python pygwytracing.py` / `python topostats/topotracing.py`
- Config file (original config file used)
- View output image "01-raw_heightmap.png"

**Expected behavior**
The raw AFM data before any processing should be shown in this image.

**Output**
Output image attached below.
![01-raw_heightmap](https://user-images.githubusercontent.com/91465918/170253762-e4723480-3b48-40e2-a89b-c7c73bc370f0.png)

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - OS: MacOS
 - topostats version: bf56931 (HEAD -> dev, origin/dev) Merge pull request #155 from AFM-SPM/ns-rse/90a-refactor-classes.
 - Python version: 3.8.13.
 - Packages attached.
[packages.txt](https://github.com/AFM-SPM/TopoStats/files/8770764/packages.txt)

**Additional context**
N/A

**Comment by bobturneruk** [comment]
Can you share the file, please? Has the file perhaps been edited before being used with topostats?

**Comment by MaxGamill-Sheffield** [comment]
@bobturneruk I'm not sure how to share the spm files on GitHub, but the file is the mincircle.spm that was shipped with TopoStats and looks like this when loaded into gwyddion

<img width="777" alt="Screenshot 2022-05-25 at 12 57 14" src="https://user-images.githubusercontent.com/91465918/170256884-3b8d3a9c-2448-40dd-970e-6a5f833613ae.png">

**Comment by ns-rse** [comment]
Just noticed this. The current first image I could get to plot was `pixels` as trying to plot the results of `load_scan()` stored in `self.images["scan_raw"]` (see line 97 of `filters.py`) resulted in and error...

```
AttributeError: 'Bruker' object has no attribute 'show'
```

I've gone and read the [documentation for pySPM](https://nbviewer.org/github/scholi/pySPM/blob/master/doc/pySPM%20Documentation.ipynb) and see it includes an example of plotting extracted channels so will try and use that as a basis to get the correct image out.
