### ISSUE TITLE
Dev: Minimum bounding box plot showing wrong bounding box

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#160]
**Describe the bug**
The plots showing the minimum bounding box does not show the correct minimum bounding box. However, values obtained for the bounding length and width are from the correct bounding box.

**To Reproduce**

- Command used to run topostats:  `python pygwytracing.py` / `python topostats/topotracing.py`
- Config file: default config file 
- Processed file: the standard minicircle.spm file
- Observe "minimum_bbox.png" plot output for grain 11

**Expected behavior**
The plot produced for each grain labeled "minimum_bbox.png" (image attached) should look similar to the blue line and not the output orange one.
This is because the minimum bounding width is the "narrowest street the car can drive down" and as should be the smallest dimension of any box that covers the molecule. 
<img width="630" alt="Screenshot 2022-05-26 at 12 58 20" src="https://user-images.githubusercontent.com/91465918/170488717-46dc3a53-1ec8-481d-9fec-0bae93baf79e.png">

**Output**
The plot output for grain 11 is shown below, which does not look like the smallest bounding width.
![minimum_bbox](https://user-images.githubusercontent.com/91465918/170490680-7719bc76-14b8-4d11-a72c-34d7a1c89341.png)
The smallest bounding box statistics are calculated correctly and shown below.
![image (2)](https://user-images.githubusercontent.com/91465918/170494217-1e878abe-ab23-4eed-b416-0fdbb0826851.png)

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - OS: MacOS
 - topostats version: bf56931 (HEAD -> dev, origin/dev) Merge pull request #155 from AFM-SPM/ns-rse/90a-refactor-classes
 - Python version: 3.8.13

**Comment by SylviaWhittle** [comment]
The calculations behind finding the minimum bounding box are correct, the script that I use to plot the bounding box has a bug in it where the box that is plotted is not the minimum bounding box. I suggest that we remove the plotting since this was a feature that was solely used for development purposes.

**Comment by MaxGamill-Sheffield** [comment]
we don't make these plots anymore, @SylviaWhittle sure the issue was in the plotting and not the ferets
