### ISSUE TITLE
Dev: Mismatch between new and old TopoStats statistics

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#171]
**Describe the bug**
Although some tolerance can be made when comparing the statistics between different versions of TopoStats, some of these are quite far out. Additionally, One would expect that when inserting the same grains and "gaussian filtered" image at the appropriate points, the end result should be identical. However, the following are not:
- Mean height
- Median height
- Maximum height
- Mean radius

**To Reproduce**
- Download config file: [example.txt](https://github.com/AFM-SPM/TopoStats/files/8853606/example.txt)
- Run topostats with `python pygwytracing.py` on minicircle.spm
- Compare output file with againt that of old TopoStats: [TopoStats.csv](https://github.com/AFM-SPM/TopoStats/files/8853408/TopoStats.csv)

Additionally, to compare the same [image](https://drive.google.com/file/d/19i5ionLmqGscFTCgj7dj0rEAwjMQNMRI/view?usp=sharing) and [grains](https://drive.google.com/file/d/1Q8akTKyfgGw5jNrbczVv5yLA50myQlal/view?usp=sharing):
- Insert into new TopoStats topotracing.py line 163 & 164: 
`ts_img = np.transpose(np.loadtxt('data_field.txt'))*1e9`
`ts_label = np.loadtxt('minicircle.spm_grains.txt').astype(int)`
- Replace calls to the original data at:
`grainstats = GrainStats(
       #data=grains.images["gaussian_filtered"],
       data=ts_img,
       #labelled_data=grains.images["labelled_regions"],
       labelled_data=ts_label,`
- Run topostats with `python pygwytracing.py` on minicircle.spm
- Compare output file with againt that of old TopoStats: [TopoStats.csv](https://github.com/AFM-SPM/TopoStats/files/8853408/TopoStats.csv)

**Expected behavior**
In the first case, all results should be near.
In the second case I'd expect results height-based results to be identical.

**Output**
Using a [comparison script](https://github.com/MaxGamill-Sheffield/Deep-AFM/tree/testing_remove_gwy/Helper%20Scripts/testing_topo) and the [new output stats file](), the differences can be seen below when using the same image and grains:
<img width="882" alt="Screenshot 2022-05-27 at 14 15 30 (2)" src="https://user-images.githubusercontent.com/91465918/172415408-97cf5802-6b01-4e62-b970-614a98509bb2.png">

**Your computer configuration (please complete the following information):**
 - OS: MacOS 12.4
 - topostats version: 30197a6 (HEAD -> dev, origin/dev) Merge pull request #161 from AFM-SPM/SylviaWhittle/158-masking-not-applied
 - Python version: 3.8.13
 
**Additional context**
Neil has done some good work on this found [here](https://github.com/ns-rse/org/blob/main/topostats/concordance/concordance.org)

**Comment by ns-rse** [comment]
Closing as agreed this has been dealt with and results are comparable.
