### ISSUE TITLE
Add a command line interface

### ISSUE THREAD

**Issue by bobturneruk** [AFM-SPM/TopoStats#18]
argparse (https://docs.python.org/3/library/argparse.html) is a od way of turning command line arguments into python variables.

**Comment by bobturneruk** [comment]
https://click.palletsprojects.com/en/8.0.x/ may be better

**Comment by JoeBeton** [comment]
Can this issue be closed since introduction of cfg file?

**Comment by Jean-Du** [comment]
I think it can be closed too
