### ISSUE TITLE
Require re-approval of Pull Requests after subsequent commits.

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#181]
Currently a Pull Request can be approved, subsequent changes can be made to a branch and pushed and, providing the tests pass, the pull request can be merged.

This can cause problems as changes are not reviewed and might introduce undesired effects.

Reviewers can be stricter and not approve Pull Requests until all changes are incorporated but as far as I can tell after approval its still possible to push subsequent commits and merge them.

**Comment by bobturneruk** [comment]
If contributors restrict their changes to dealing with review comments, this shouldn't be a problem. Happy to discuss.

**Comment by ns-rse** [comment]
I'd hope that is the case but it might not always be. Perhaps the way to solve it is simply not to approve if suggestions have been made. :thinking:

**Comment by bobturneruk** [comment]
It's worth a chat, I think. All the other projects I work on as set up as topostats is now.

**Comment by ns-rse** [comment]
Closing, this is currently in place I think as we have the following in the branch protection rules

> + [x] Require approval of the most recent reviewable push
> Whether the most recent reviewable push must be approved by someone other than the person who pushed it.
