### ISSUE TITLE
Add input (and output?) config files

### ISSUE THREAD

**Issue by bobturneruk** [AFM-SPM/TopoStats#19]
YAML, TOML and JSON are potential options for this. TOML is probably the most readable, YAML is more broadly used and JSON is very widely used but has a some extra syntax which might make it harder to read. The first step down this road would be to capture what inputs are required to make topostats run. Maybe start listing these below?

**Comment by derollins** [comment]
Since the stats output files are JSON is there an advantage to using them as config files or would it be better to use a different type?

**Comment by bobturneruk** [comment]
I think this was resolved by #49 - if this is not the case, @SylviaWhittle please open a new issue on what still need to be done.
