### ISSUE TITLE
Issue with maximum and minimum bounding lengths

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#219]
**Describe the bug**
There was a misunderstanding when implementing the max and min bounding lengths in `calculate_aspect_ratio`. I understood these values to be the width and length of the smallest bounding box that can be formed around a grain, however this is incorrect. These values are actually the width (smallest side) of the smallest bounding box, and the length (longest side) of the **largest** bounding box. 

<img width="748" alt="image" src="https://user-images.githubusercontent.com/86117496/179483898-1b0d4924-f9a7-49db-808c-79fe555398ca.png">

@Jean-Du could you confirm if I am understanding this correctly please.

**To Reproduce**

N/A

**Expected behavior**
N/A

**Output**

N/A

**(Not required if using Docker) Your computer configuration (please complete the following information):**
Hardware irrelevant.

**Comment by Jean-Du** [comment]
I think this diagram might make it clearer; the smallest bounding distance should be the smallest width of all possible bounding boxes, and the largest bounding distance should be the longest length among all possible bounding boxes; @derollins has a hand drawn diagram for this too that might be useful

**Comment by SylviaWhittle** [comment]
Resolved as of #219. I thought this should have been auto-closed since I added the 'Resolves #219' line in the pull request.
