### ISSUE TITLE
Reformat readme

### ISSUE THREAD

**Issue by bobturneruk** [AFM-SPM/TopoStats#22]
Add headings and other nice formatting.

**Comment by ns-rse** [comment]
This has been done on the `dev` branch and merged with #73 but I can't currently see a way for me to close issues.

**Comment by bobturneruk** [comment]
Specifically, I think a lot of the explanatory text should be migrated to Sphinx and form part of the readthedocs site, leaving a minimal readme on GitHub.

**Comment by bobturneruk** [comment]
Resolved via multiple PRs.
