### ISSUE TITLE
Colorbar "False" option doesn't work

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#222]
**Describe the bug**
When setting `colourbar : False` in the config file, all images still have a colour bar.

**To Reproduce**
Setting `colourbar : False` in the config file, all images still have a colour bar.

**Expected behavior**
No images should have a colour bar.

**Output**
 All images still have a colour bar.

**Additional context**
The test for this option passes meaning its not being passed through the main script correctly.

I think it's because `colorbar` is not referenced within the `process_scan` function in `run_topostats.py`

**Comment by SylviaWhittle** [comment]
Resolved as of #223 ✅
