### ISSUE TITLE
Convert absolute_smallest_grain_size in pixels to SI units

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#268]
Currently the `absolute_smallest_grain_size` set in the `grains` class for excluding noise is in pixels. It would be preferable to have this in nanometers.

**Comment by ns-rse** [comment]
See also #243

**Comment by bobturneruk** [comment]
This is to remove small bits of crap in the image, not digital artefacts.

**Comment by MaxGamill-Sheffield** [comment]
Discussed with Alice, moving away from Milestone 1 until file formats implemented and a pixel-wise unit can possibly be extracted

**Comment by MaxGamill-Sheffield** [comment]
Seems like this is in `nm` at least:
```
remove_small_objects(
                image,
                min_size=(self.minimum_grain_size * self.pixel_to_nm_scaling),
                **kwargs,
            )
```

This function comes from https://scikit-image.org/docs/stable/api/skimage.morphology.html#skimage.morphology.remove_small_objects and inputs an integer size so it may only need an int wrapper.
