### ISSUE TITLE
Area thresholding to find grains of interest

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#281]
**Is your feature request related to a problem? Please describe.**
If data consists of DNA and protein for example, current height thresholding may always identify both due to their heights. But if only the protein is wanted to be masked and statistics for this obtained, there is no way do distinguish them based on a useful statistic such as area.

Additionally, if a user wanted to only examine single molecules, this same area thresholding should be used to get rid of "joined" molecules where the single grain covers two close molecules, as this would skew the produced statistics.

**Describe the solution you'd like**
Upper and lower thresholding based on the grain areas.

**Describe alternatives you've considered**
None.

**Additional context**
This is also related to an issue in which grains covering close molecules have no way of being removed.

**Comment by Jean-Du** [comment]
For example, with these files, https://drive.google.com/drive/folders/1oBkplDNRqFBXej33QYsbhxFAxmrcTLtB, the user might want to do any of these:
1) Select only the joined molecules, as in these images https://drive.google.com/drive/folders/1eLNmzx7bjfTvnR2e1qJLGBJvHjkBadik
2) Select only the non-joined molecules, as in these images 
https://drive.google.com/drive/folders/1l12dfO9gP1V5N-u0cpXv4LlrZB8vQyTY
3) Select all of them

**Comment by MaxGamill-Sheffield** [comment]
These are the lines I've been looking at:
<img width="921" alt="Screenshot 2022-09-13 at 11 27 29" src="https://user-images.githubusercontent.com/91465918/189878513-9d5173c7-9757-43c9-b957-3b5600d2c1f2.png">
