### ISSUE TITLE
Remove `background` from config

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#288]
**Is your feature request related to a problem? Please describe.**
From #269 , it was decided the background value is always `0` and thus, can be removed from the config file in order to reduce its complexity. 

This would also require one to replace line 156 in `grains,py` to `background=0` or remove it entirely.

**Comment by ns-rse** [comment]
Now that validation has been introduced (see #299 and #303) this will also require the removal of the following line (30)...

```yaml
  background: 0.0
```

...from the following files

* [ ] `topostats/default_config.yaml`
* [ ] `tests/resources/sample_config.yaml`
* [ ] `tests/resources/process_scan_config.yaml`
* [ ] `config/example.yaml` (not so important as this should be removed once #305 is merged.

The validation file will also need line 88 removing

* [ ] `topostats/validation.py`

And the doc-string on lines 72-72 

* [ ] `topostats/grains.py`
