### ISSUE TITLE
Improve flattening

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#298]
**Describe the bug**
Flattening is not quite as good as we require. We propose to create a set of tests to determine the quality of, and diagnose problems in flattening.

- Further tests for flattening
- Demos of what it can and cannot currently flatten
- Add the 'flatten base' feature from Gwyddion. (http://gwyddion.net/documentation/user-guide-en/leveling-and-background.html) this paper has lots of information on it too: (https://www.beilstein-journals.org/bjnano/content/pdf/2190-4286-3-84.pdf)

Feel free to assign yourself too - I don't want to steal all the fun tasks!

**Comment by MaxGamill-Sheffield** [comment]
I've made a little comparison table of the 3 flattening procedures between Old TS, what's in the TopoStats paper, and what we have at the minute in new TopoStats if this helps with the procedure:
<img width="427" alt="Screenshot 2022-10-03 at 16 07 24" src="https://user-images.githubusercontent.com/91465918/193611606-35bc1d6c-156f-4adf-9a44-39e5634fd8da.png">

**Comment by MaxGamill-Sheffield** [comment]
I had a meeting with Alice where she has suggested the following instead of flatten base as this seemed to work well on images within Gwyddion:
- Align rows via Median of Differences
- Level
- Mask
- Align rows viaMedian of Differences
- Level
- Re-mask
- Align rows via Median

**Comment by ns-rse** [comment]
Closed with #351

**Comment by MaxGamill-Sheffield** [comment]
Removed gdrive test data
