### ISSUE TITLE
Validate Input

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#299]
**Is your feature request related to a problem? Please describe.**
We should create a system to validate the input values that are given in the config file. Ie - checking that `size_threshold` is a number ie `54.2`, and not `'hippopotamus'`, as currently we do not check that users' inputs are valid. This can cause confusion and unexpected errors, resulting in being uncertain as to why a program crashes / doesn't behave as expected.

This could go in the `IO.py` file?

**Describe alternatives you've considered**
N/A

**Comment by ns-rse** [comment]
Closed by #303
