### ISSUE TITLE
Reorder the 'grains' section of the config file

### ISSUE THREAD

**Issue by Jean-Du** [AFM-SPM/TopoStats#319]
**Is your feature request related to a problem? Please describe.**
At the moment, the 'grains' section contains options for both height-based selection and area-based selection, and it is not very clear which one each line refers to, and this could cause confusion to users unfamiliar with the project.

**Describe the solution you'd like**
Reorder the parameters in the 'grains' section of the config so that all height-based entries are in one place and all area-based entries are in another, with clearer commenting showing which one is which.

**Describe alternatives you've considered**
I considered creating nested subsections within the 'grains' section, but this would cause unecessary complications. 

**Additional context**

**Comment by MaxGamill-Sheffield** [comment]
Just incase you've missed some of the recent updates, there is no example.yaml config file anymore. 

These changes should instead be made to `topostats/default_config.yaml`.

**Comment by Jean-Du** [comment]
@MaxGamill-Sheffield Thanks a lot! I'll keep that in mind

**Comment by ns-rse** [comment]
Close by #328
