### ISSUE TITLE
Rename '14-small_objects_removed' in the image output

### ISSUE THREAD

**Issue by Jean-Du** [AFM-SPM/TopoStats#361]
**Is your feature request related to a problem? Please describe.**

At the moment, the image output '14-small_objects_removed' seems to be the result of both 'remove_small_objects' and 'area_thresholding', i.e. grains are removed both for being too small or too large, so this needs to be renamed.

**Describe the solution you'd like**
Rename '14-small_objects_removed' into something like '14-area_thresholding' to reflect the actual changes involved.

**Describe alternatives you've considered**

**Additional context**

**Comment by ns-rse** [comment]
Closing, a [search](https://github.com/search?q=repo%3AAFM-SPM%2FTopoStats%2014_small_objects_removed&type=code) of the repository suggests this name is no longer used...

```bash
❱ grep 14 topostats -R
topostats/theme.py:                (0.714052, 0.725806, 0.725806),
topostats/theme.py:                (0.971401, 0.996006, 0.996006),
topostats/theme.py:                (0.611588, 0.334114, 0.334114),
topostats/theme.py:                (0.714052, 0.527471, 0.527471),
topostats/theme.py:                (0.971401, 0.993565, 0.993565),
topostats/theme.py:                (0.714052, 0.268, 0.268),
topostats/theme.py:                (0.971401, 0.990347, 0.990347),
topostats/plotting_dictionary.yaml:  filename: "14-scar_mask"
topostats/topostats.mplstyle:#contour.algorithm:          mpl2014 # {mpl2005, mpl2014, serial, threaded}
topostats/topostats.mplstyle:#pdf.use14corefonts: False
topostats/run_topostats.py:# Ref : https://stackoverflow.com/a/57799639/1444043
```
