### ISSUE TITLE
Enable GitHub discussions

### ISSUE THREAD

**Issue by bobturneruk** [AFM-SPM/TopoStats#38]
Great to see the engagement here! https://github.com/AFM-SPM/TopoStats/issues/26

To make things easier in future, I think we should enable **discussions** for, well, discussions. And keep **issues** for bug reports, enhancements and feature requests. This means that we'd need, at least, some guidance in the readme on this, and perhaps later some issue templates. What do you think @alicepyne? I can turn on discussions with a button push - perhaps someone else in the team could look at the readme?

**Comment by alicepyne** [comment]
Sounds perfect - definitely turn the discussion on!

**Comment by bobturneruk** [comment]
Now enabled.
