### ISSUE TITLE
Statistics and image output for single molecules

### ISSUE THREAD

**Issue by Jean-Du** [AFM-SPM/TopoStats#382]
**Is your feature request related to a problem? Please describe.**
At the moment, all output are either directory based or file based. An optional molecular level output is needed, especially after PR #365 is merged

**Describe the solution you'd like**
I am not sure what is the best way to approach this. With in each file-based directory in the output, we could have subdirectories named by the molecule number, eg under output/processed/examplespmfile/1, we have the cropped image, curvature plot, pixel level statistics for that one molecule.
Alternatively, we can also have directories named 'curvature' 'cropped images' etc instead of molecule number based directories.

**Describe alternatives you've considered**

**Additional context**

**Comment by MaxGamill-Sheffield** [comment]
In terms of the single molecule level statistics, I think we came to the conclusion that a JSON file would be best as csv/dataframes wouldn't work well with so many statistics at different levels

**Comment by MaxGamill-Sheffield** [comment]
Single object / molecule / branch etc stats either stored in own file or in the `.topostats` file
