### ISSUE TITLE
Unrotate the image output from dnatracing.py

### ISSUE THREAD

**Issue by Jean-Du** [AFM-SPM/TopoStats#383]
**Is your feature request related to a problem? Please describe.**
At the moment, the image output in dnatracing.py (turned off by default) are rotated by 90 degrees, possibly due to the structure of numpy arrays. This needs to be undone for consistency reasons.

**Describe the solution you'd like**
Produce images from dnatracing.py that are in the same orientation as the main image output.

**Describe alternatives you've considered**

**Additional context**

**Comment by MaxGamill-Sheffield** [comment]
No longer an issue
