### ISSUE TITLE
Incorrect naming of output files when input files have multiple `.`s in them.

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#391]
**Describe the bug**

While the issue of the crashes when processing files with multiple `.`s in the file name was resolved in #271, the strings following the second `.` is lost. This second string is important for distinguishing different iterations / versions of similar scans. 

Currently, if one processes two images with the same name before the second `.`, but different after the second `.`, the second processed image will be saved with the same name as the first and so overwrite the data of the first.

Example here:

File names that differ only in post-second `.` text:
<img width="471" alt="image" src="https://user-images.githubusercontent.com/86117496/206152691-132178e1-2563-49aa-a91b-a6c23bf99ecf.png">

Output data:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/86117496/206152854-6d392bc5-b025-4029-bbe9-915ed95c9b55.png">

**To Reproduce**

Run two images with the same name before the second `.`, but differing after the second `.`. Notice that the second image overwrites the output for the first image.

**Expected behavior**
The output images should retain the entire names, but have the second `.` removed. Perhaps like this:

in:
```
data.01.spm
```

out:
```
data01.png
```

**(Not required if using Docker) Your computer configuration (please complete the following information):**
 - MacOS
 - topostats version: 2.0.0
 - Python version: 3.10.

**Comment by MaxGamill-Sheffield** [comment]
I remember this being an issue a while ago and I thought it was resolved. Additionally, I don't see this on the branch I'm working on (the 183 branch which hasn't touched plotting):
<img width="169" alt="Screenshot 2022-12-08 at 17 07 13" src="https://user-images.githubusercontent.com/91465918/206517593-13839f0c-bd5f-41c2-baa3-72f5a13c9dcc.png">
<img width="306" alt="Screenshot 2022-12-08 at 17 10 57" src="https://user-images.githubusercontent.com/91465918/206518399-be8c010c-185b-4740-ac09-61f1f177aa5e.png">

Are there specific circumstances where this occurs?

**Your computer configuration:**
- MacOS
-  TopoStats version: 305d481 (HEAD -> maxgamill-sheffield/183-dnatracing-refactor, origin/maxgamill-sheffield/183-dnatracing-refactor) Removed troubleshooting savetxt's
- Python: 3.10.6

**Comment by SylviaWhittle** [comment]
That is very interesting. I know why it occurs on my system:

In `process_scan`, on line `170`:
```
    filename = image_path.stem
```

Now when I run topostats on the image in the screenshot, `image_path` is the file name, **without** the `.spm` extension. Now when `.stem` is called on it, it fetches the string before the `.`, but the only `.` is the one in the middle of the file name, so the name gets truncated into just the stuff before the first `.`.

This is all on the scars branch, but I wouldn't have thought that it would change between scars and main since I haven't edited anything to do with the file handling. I will check main though too now you mention it.

**Comment by MaxGamill-Sheffield** [comment]
This may also be addressed in the asd PR because I add more functions to `io.py`
