### ISSUE TITLE
Make the config file setup process easier

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#393]
**Is your feature request related to a problem? Please describe.**
As we have seen in the discussion board, generating a configuration file in an appropriate place can be a challenging task for new users, especially when they are unfamiliar with the terminal. I propose that we create a command that makes a copy of the default config file in the current directory:

```
run_topostats --make-config
```

This could place a default config file called `config.yaml` in the current directory. 

This may help to alleviate some user frustration and confusion when getting started.

**Comment by ns-rse** [comment]
Out of curiosity how often are people going to want to use their own configuration file?

I'm capturing the code from our conversation on this the other day.

## Generating configuration file.

Adding the following argument under `topostats/run_topostats.py` would add an option `--create_config_file` to `run_topostats`...

```python
if args.create_config_file:
    write_yaml(config, output_dir=args.create_config_file)
    LOGGER.info(f"A sample configuration has been written to : {args.create_config_file}/config.yaml)")
    LOGGER.info("Please refer to the documentation on how to use the configuration file : \n\n"     
        "https://afm-spm.github.io/TopoStats/usage.html#configuring-topostats\n"
        "https://afm-spm.github.io/TopoStats/configuration.html")
    exit()
```

Under `main()` this would over-ride doing anything if the following clause is added at the start.

```python
if args.create_config_file:
    write_yaml(config, output_dir=args.create_config_file)
    LOGGER.info(f"A sample configuration has been written to : {args.create_config_file}/config.yaml)")
    LOGGER.info("Please refer to the documentation on how to use the configuration file : \n\n"     
        "https://afm-spm.github.io/TopoStats/usage.html#configuring-topostats\n"
        "https://afm-spm.github.io/TopoStats/configuration.html")
    exit()
```

Rough and ready so the above will need testing and importantly the `docs/usage.md` updated to reflect this feature.

**Comment by SylviaWhittle** [comment]
After asking the group, we think that users will be wanting to use their own config file upwards of 70% of the time.
