### ISSUE TITLE
Rename 'upper' and 'lower' in the config file into 'above' and 'below'

### ISSUE THREAD

**Issue by Jean-Du** [AFM-SPM/TopoStats#394]
**Is your feature request related to a problem? Please describe.**
The words 'upper' and 'lower' may be a point of confusion for new users, especially in the lines
```
absolute_area_threshold:
    upper: [ 500, 800 ] # above surface [Low, High] in nm^2 (also takes null)
    lower: [ null, null ] # below surface [Low, High] in nm^2 (also takes null)
```
 where there are higher and lower limits within each section.

**Describe the solution you'd like**
Rename 'upper' into 'above' or 'above surface', and 'lower' into 'below' or 'below surface', so that it's clear to users what they refer to, and they won't be confused with higher and lower thresholds.

**Describe alternatives you've considered**

**Additional context**

**Comment by ns-rse** [comment]
As discussed 2023-02-28 we need clear documentation of what each parameter represents and how they relate to each other.

To this end bulking out the `docs/configuration.md` with detailed descriptions is fundamental, and short comments in the `topostats/default_config.yaml` would be appropriate too. What the names should be would I hope be clarified by having clearer descriptions of the purpose and if these values are to be renamed that isn't actually a huge task (in most IDEs you can rename variables across projects in a few seconds).

There are variables under both `filters` and `grains` that are affected by this issue.
