### ISSUE TITLE
Rename config.yaml to settings.yaml for increased friendliness 

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#395]
**Is your feature request related to a problem? Please describe.**
A suggestion from @derollins, to make the editing of the config less intimidating to new users. Would welcome opinion on this.

**Comment by ns-rse** [comment]
Personally I consider config[uration] and settings to be synonymous.

**Comment by ns-rse** [comment]
Closed by #398 

A configuration file of any name can be created with the new configuration option `--create-config-file`.
