### ISSUE TITLE
Clarify install docs (paths, cwd, downloadable config file, broken link)

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#396]
**Describe the bug**

- [x] . - relative path clarification as some users are unsure why/what the dot is and why TS can’t find their files
- [x] Additionally, add pwd command to show where you are in the terminal, and explain that with pip install topostats , users only need a config file and data folder
- [x] Need to ensure that config file is downloadable or have copy-paste instructions. There is currently an issue where the config file linked in the docs and the file+validation on PyPi are different so copy pasting this gives errors
- [x] [Readthedocs : TopoStats](https://topostats.readthedocs.io/en/dev/) (broken link) > should go to 2.0.0 docs not 1.0

**Expected behavior**
A clear and concise description of these instructions in the docs.

**Comment by ns-rse** [comment]
Ah, I've already started doing most of this as part of #393.

**Comment by MaxGamill-Sheffield** [comment]
@ns-rse Which have you started? I've added a few bits to on a branch but can back off?

**Comment by ns-rse** [comment]
Closed by #398 

Documentation updated with...

* [x] Explanations on very basic command line usage.
* [x] Added function to generate configuration file to `run_topostats --create-config-file <filename>.yaml`
* [x] Removed broken link.
