### ISSUE TITLE
Add molecule number in the all_statistics.csv spreadsheet

### ISSUE THREAD

**Issue by Jean-Du** [AFM-SPM/TopoStats#403]
**Is your feature request related to a problem? Please describe.**
Introduce a column of molecule number in the all_statistics.csv spreadsheet and make sure it is consistent with the molecule number in the cropped out images of all the grains, so that the user can look up the statistics for each individual grain.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by SylviaWhittle** [comment]
I think this is a reasonable and sensible feature to add. Can't see any issues with it, will help with debugging too.

**Comment by ns-rse** [comment]
I thought I had ensured these were included as I'm sure I've added `.to_csv(<filename>, index=True)` option in the past.

**Comment by Jean-Du** [comment]
It seems that there is still a mismatch between the molecule number in `dnatracing.py` and the molecule number in the statistics output. @MaxGamill-Sheffield has tested this with `minicircles.spm` by increasing the `purge_obvious_crap` threshold to 60 and has prodcued the following files:
[no_lils.csv](https://github.com/AFM-SPM/TopoStats/files/11454511/no_lils.csv)
[lils.csv](https://github.com/AFM-SPM/TopoStats/files/11454512/lils.csv)
![Screenshot 2023-05-11 at 17 22 34](https://github.com/AFM-SPM/TopoStats/assets/58240320/e9d33888-fef2-4ba2-a01f-a971b5412c18)
![minicircle_upper_masked](https://github.com/AFM-SPM/TopoStats/assets/58240320/3b5177bb-bbe5-467c-bc0b-de05b1c34427)

**Comment by ns-rse** [comment]
I think I've sussed this out but I've a question...

If a grain has statistics but is removed because of size during `dnaTrace` processing (aka `purge_obvious_crap`) is it desirable to have the grain statistics reported but no tracing statistics?

**Comment by Jean-Du** [comment]
Hi @ns-rse , yes, I believe that would be desirable
