### ISSUE TITLE
Skeletons appear broken when plotting

### ISSUE THREAD

**Issue by MaxGamill-Sheffield** [AFM-SPM/TopoStats#406]
**Describe the bug**
Single pixel thick skeletons appear broken on the produced plots, this seems to be due to the reduced dpi.

**To Reproduce**
This has been made to break-up the knots and cats branch. I have obtained skeletons from dnatracing, and used the skeleton as a mask for the `data2` input to `plottingfuncs.Images`

**Expected behavior**
Skeletons should be visible:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/91465918/208094121-2ebfce31-d884-4a24-80f8-4ebe879a06eb.png">

**Output**
Skeletons seem broken:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/91465918/208094096-45c6ff83-6c84-4e8d-905e-eb03569435b9.png">

**Comment by ns-rse** [comment]
What version/branch/commit are you using? Is this TopoStats 2.0.0 or another branch?

If its that with refactoring of DNATracing that you've been working on which method of skeletonisation are you using? Is it "Joe's" with the pruning and could that be a factor? Is the expected image above a single-pixel plot and if so how was it skeletonised?

**Comment by MaxGamill-Sheffield** [comment]
This is a dpi error and fixed with #409 (pending weird test error resolution)
