### ISSUE TITLE
Add link to paper

### ISSUE THREAD

**Issue by bobturneruk** [AFM-SPM/TopoStats#41]
How to cite (title, authors, journal) + link:

https://figshare.shef.ac.uk/articles/software/TopoStats_-_an_automated_tracing_program_for_AFM_images/13103327/1https://figshare.shef.ac.uk/articles/software/TopoStats_-_an_automated_tracing_program_for_AFM_images/13103327/1

To be added to readme.

**Comment by ns-rse** [comment]
I've found the citation and added this to a branch I'm working on but don't currently have the ability to assign the task to myself.
