### ISSUE TITLE
Publish TopoStats 2.0 to Sheffield ORDA

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#418]
TopoStats (<v2.0) is published to [Sheffield ORDA](https://figshare.shef.ac.uk/articles/software/TopoStats_-_an_automated_tracing_program_for_AFM_images/13103327).  With the release of v2.0 this record either needs updating or a new entry making.

**Comment by ns-rse** [comment]
See [Release to ORDA](https://github.com/RSE-Sheffield/release_to_ORDA).

**Comment by alicepyne** [comment]
Will probably need to happen just after release
