### ISSUE TITLE
Flag or skip images that are too small

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#470]
**Is your feature request related to a problem? Please describe.**
Some images are just too small for the flattening algorithms to handle. This can cause errors to be thrown up in otherwise perfectly functional code, as with #381, which failed to fit a numpy polyfit to an image that was two pixels tall, as we would expect.

**Describe the solution you'd like**
Add a step to check if the image is smaller than say, 10x10, and if so, skip that image with a note in the console and mark it as failed to process.

**Comment by ns-rse** [comment]
Do we have, or could we generate, parameters for what constitutes "too small"?

**Comment by SylviaWhittle** [comment]
Completed as of #545
