### ISSUE TITLE
Molecule trace x, y, z coordinates

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#488]
It would be good to output statistics for the z-height of the molecule traces from `dnatracing`. Probably as part of a csv file? This might mean that a new csv file has to be made to hold all the trace coordinates.

**Comment by ns-rse** [comment]
JSON might be more succinct, will tag this onto #183 as it should be done under the refactored framework rather than the current module.

**Comment by ns-rse** [comment]
#595 is a duplicate.

CSV is probably a better solution as it would be easier for more people to work with.
