### ISSUE TITLE
pprint() show output; -q flag no longer silent

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#496]
### pprint()

Updating logging to allow `LOGGER.debug()` has left a `pprint()` statement in `run_topostats()` this outputs to `stdout` even though its wrapped within `LOGGER.debug(f"Configuration after update         : \n{pprint(config, indent=4)}")` (see line 213).

The solution appears to be to use [`pprint.pformat()`](https://stackoverflow.com/a/11093247) instead.

### `-q/--quiet` no longer silent

This flag no longer results in silent behaviour. Two options...

1) Remove flag and use `--log-level` which would be my preference (requires updating documentation).
2) Reinstate and have the `-q`/`--quiet` option set the log-level to `warning`. Less desirable to me as its duplication of options.

**Comment by SylviaWhittle** [comment]
Personally I prefer the first option, as I don't see a great need for options regarding console outputs, and it is a lot neater in my opinion.
