### ISSUE TITLE
Image processing for files without detected grains

### ISSUE THREAD

**Issue by derollins** [AFM-SPM/TopoStats#53]
When the code doesn't detect any grains in an spm file the image isn't processed because of:

`          # if there's no grains skip this image

            if number_of_grains == 0:

                continue`
in the main script.

If this is commented out then no `cropped_grains` are made and 
`            # Create cropped datafields for every grain of size set in the main directory

            bbox, orig_ids, crop_ids, data, cropped_grains, cropwidth_pix = boundbox(cropwidth, datafield, grains, dx,
                                                                                     dy, xreal, yreal, xres, yres)`
also needs commented out too, which prevents cropped images being created later.

It would be helpful if all images were processed whether or not they had grains.

**Comment by MaxGamill-Sheffield** [comment]
Resolved in new topostats. Blanks can be processed.
