### ISSUE TITLE
Obtain plot x,y data from plotting.py plots

### ISSUE THREAD

**Issue by SylviaWhittle** [AFM-SPM/TopoStats#56]

**Comment by SylviaWhittle** [comment]
Added this functionality in the GetPlotData branch. It is complete however it is not currently needed in the main branch. Will need merging in the long term.

**Comment by ns-rse** [comment]
Hi @SylviaWhittle 

Do you think we can close this issue now? You've introduced saving of data to Numpy arrays elsewhere and started developing the HDF4 `.topostats` file format so I think that covers the need to extract the data.

**Comment by SylviaWhittle** [comment]
trace, spline/smoothed points are available now in the topostats file, added as part of the tracing refactor #932
