### ISSUE TITLE
Handle duplicate statistics that arise from multiple molecules within a single grain

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#644]
When a grain consists of multiple molecules (either DNA or protein) these will be separated and tracing statistics calculated for each.

These would retain the grain number and add an additional suffix (or column) which indicates which molecule within the grain the data is.

However, when merging with grain statistics this then introduces duplicates (right/left join). This has the unintended consequence when plotting grain statistic summary plots that the duplicates need removing.

We need to handle this internally when plotting grain statistics that have been merged with tracing statistics.

**Comment by MaxGamill-Sheffield** [comment]
multiple molecules are handled in seperate files with the additon of #932, only all grain statistics should be added to the grainstats file so this would include only the combination of a single object per mask.

This will be split out further in the future but with the addition of object classes.
