### ISSUE TITLE
Improved binary masking to retain details from grains

### ISSUE THREAD

**Issue by llwiggins** [AFM-SPM/TopoStats#652]
Current binary masking in TopoStats causes loss of fine details from the original grain (such as holes or merging of close strands) and this causes downstream issues for detection of nodes/branches.

Improved binary masking involves ridge detection filters to enhance grain boundaries ahead of masking, example below:

Original image:
<img width="224" alt="image" src="https://github.com/AFM-SPM/TopoStats/assets/91545985/b562a191-f988-4df7-8611-1d5749f38b95">

Grain mask:
<img width="224" alt="image" src="https://github.com/AFM-SPM/TopoStats/assets/91545985/7e21603a-00a8-4e3b-a571-a8f6d725a72b">

Binary mask following ridge detection:
<img width="186" alt="image" src="https://github.com/AFM-SPM/TopoStats/assets/91545985/bb2dec30-72b8-43ea-a642-15e37817ce5e">

Often ridge detection followed by binary masking causes unwanted gaps within grain masks, currently working on a solution for this.

**Comment by MaxGamill-Sheffield** [comment]
Can this be closed with the addition / creation of a pull-request with @SylviaWhittle's UNet code?
