### ISSUE TITLE
Remove Gwyddion - Connected components

### ISSUE THREAD

**Issue by bobturneruk** [AFM-SPM/TopoStats#67]
## Connected components (grains)

Gwyddion has `grains_mark_height`, `grains_remove_touching_border`, `grains_remove_by_size`, `number_grains`, `grains_invert`, `grains_intersect`, `grains_get_values`

Would need to lean on https://scikit-image.org/docs/dev/api/skimage.morphology.html, https://scikit-image.org/docs/dev/api/skimage.measure.html, https://scikit-image.org/docs/dev/api/skimage.measure.html#skimage.measure.regionprops

**Comment by SylviaWhittle** [comment]
Completed as of #147
