### ISSUE TITLE
Config file - what parameters should we capture?

### ISSUE THREAD

**Issue by bobturneruk** [AFM-SPM/TopoStats#87]
Please put ideas here!

**Comment by Jean-Du** [comment]
A separate config file for the Plotting.py

**Comment by benthomasuos** [comment]
A plot theme or at least a default matplotlib colourmap with traditional AFM colourscale?

**Comment by LunchBobs** [comment]
I've been writing an ideal config file here https://drive.google.com/drive/u/0/folders/1_j4PQH0a2NxKl69coTfZ4GyXGz5CS_gr with some ideas based on what the industrial collaborators need. I've tried to comment as much as I can so it makes sense.

**Comment by bobturneruk** [comment]
Can you upload here please, @LunchBobs? This would enable more people to see and contribute...

**Comment by LunchBobs** [comment]
Sure! [Ideal pygwytracing config file.docx](https://github.com/AFM-SPM/TopoStats/files/8552330/Ideal.pygwytracing.config.file.docx)

**Comment by ns-rse** [comment]
Closing, we have a well-developed configuration file.
