### ISSUE TITLE
Remove support for Python 3.12

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#930]
In light of #927 where we have discovered a performance regression of the dependency [topoly](https://topoly.cent.uw.edu.pl/documentation.html) with Python 3.12 we should, for the better tracing work and release remove support for Python 3.12 from TopoStats until this has been resolved.

## `pyproject.toml`

```toml
requires-python = ">=3.9, <3.12"
```

## `.github/workflows/tests.yaml`

```yaml
        python-version: ["3.9", "3.10", "3.11"]
```

**Comment by MaxGamill-Sheffield** [comment]
Don't think the auto close worked here so closing as fixed in #931
