### ISSUE TITLE
Unpin dependency on topoly==1.0.2

### ISSUE THREAD

**Issue by ns-rse** [AFM-SPM/TopoStats#994]
We should soon be able to unpin the dependency on `topoly==1.0.2` as the authors have released a wheel of `topoly==1.0.4` for Windows and version for Apple ARM architecture is [in the offing](https://github.com/AFM-SPM/TopoStats/issues/927#issuecomment-2458194728).

**Comment by prubach** [comment]
The 1.0.4 Mac ARM version is also out now!
